accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
  path('signup/', views.SignUpView.as_view(), name='signup')
]

bestdish/urls.py
from django.urls import path
from . import views

app_name = 'bestdish'

urlpatterns = [
  path('', views.IndexView.as_view(), name='index'),
  path('<int:pk>/', views.DetailView.as_view(), name='detail'),
  path('create/', views.CreateView.as_view(), name='create'),
  path('<int:pk>/update/', views.UpdateView.as_view(), name='update'),
  path('<int:pk>/delete/', views.DeleteView.as_view(), name='delete'),
]

myapp/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    path('bestdish/', include('bestdish.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', RedirectView.as_view(url='/bestdish/')),
]

accounts/models.py
from django.db import models

# Create your models here.

bestdish/models.py
from django.db import models
from django.urls import reverse

class Category(models.Model):
    name = models.CharField(max_length=255)
    author = models.ForeignKey(
        'auth.User',
        on_delete=models.CASCADE,
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

class Shop(models.Model):
    name = models.CharField(max_length=255)
    address = models.CharField(max_length=255)
    author = models.ForeignKey(
        'auth.User',
        on_delete=models.CASCADE,
    )
    category = models.ForeignKey(
        Category,
        on_delete=models.PROTECT,
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('bestdish:detail', kwargs={'pk': self.pk})

accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic

class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'accounts/signup.html'

bestdish/views.py
from django.urls import reverse_lazy
from django.views import generic
from .models import Category, Shop
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied


class IndexView(generic.ListView):
  model = Shop

class DetailView(generic.DetailView):
  model = Shop

class CreateView(LoginRequiredMixin, generic.edit.CreateView):
  model = Shop
  fields = ['name', 'address', 'category'] # '__all__'

  def form_valid(self, form):
      form.instance.author = self.request.user
      return super(CreateView, self).form_valid(form)

class UpdateView(LoginRequiredMixin, generic.edit.UpdateView):
  model = Shop
  fields = ['name', 'address', 'category'] # '__all__'

  def dispatch(self, request, *args, **kwargs):
      obj = self.get_object()
      if obj.author != self.request.user:
        raise PermissionDenied('You do not have permission to edit.')
      return super(UpdateView, self).dispatch(request, *args, **kwargs)

class DeleteView(LoginRequiredMixin, generic.edit.DeleteView):
  model = Shop
  success_url = reverse_lazy('bestdish:index')

accounts/templates/accounts/signup.html
{% extends 'layout.html' %}

{% block content %}
<h1>Sign up</h1>
<section class='common-form'>
    <form method='post'>
        {% csrf_token %}
        {{ form.as_p }}
        <button type='submit' class="btn btn-outline-primary">Sign up</button>
    </form>
</section>
{% endblock %}

bestdish/templates/bestdish/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name='viewport' content='width=device-width, initial-scale=1, shrink-to-fit=no'>
    <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css'>
    <title>Bestdish</title>
    <style>body {padding-top: 80px;}</style>
  </head>
  <body>
    <nav class='navbar navbar-expand-sm navbar-dark bg-dark fixed-top'>
      <a class='navbar-brand' href='{% url "bestdish:index" %}'>Best Dish</a>
    </nav>
    <div class='container'>
      {% block content %}
      {% endblock %}
    </div>
  </body>
</html>

bestdish/templates/bestdish/shop_confirm_delete.html
{% extends 'layout.html' %}
{% block content %}
  <h1>お店情報の削除</h1>
  <p>'{{ object.name }}'を削除しますか？</p>
  <form action="" method="post" >{% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="submit delete btn btn-outline-danger">削除</button>
  </form>
  <p> </p>
  <div>
    <a href='JavaScript:history.back()' class='btn btn-outline-secondary'>&lt; 戻る</a>
  </div>
{% endblock %}

bestdish/templates/bestdish/shop_detail.html
{% extends 'layout.html' %}
{% block content %}
  <h1>{{ shop.name }}</h1>
  <div>
    <p>{{ shop.category.name }}</p>
    <p>{{ shop.address }}</p>
  </div>
  <iframe id='map'
    src='https://www.google.com/maps/embed/v1/place?key=AIzaSyBeIJWI5wdP5di8fURnQUIxABIoMAq_kvM&amp;q={{ shop.address }}'
    width='100%'
    height='320'
    frameborder='0'>
  </iframe>
  <div>
    <a href='{% url "bestdish:index" %}' class='btn btn-outline-primary'>一覧</a>
    {% if request.user.id == object.author_id %}
      <a href="{% url 'bestdish:update' shop.pk %}" class='btn btn-outline-primary'>編集</a>
      <a href="{% url 'bestdish:delete' shop.pk %}" class='btn btn-outline-danger'>削除</a>
    {% endif %}
  </div>
{% endblock %}

bestdish/templates/bestdish/shop_form.html
{% extends 'layout.html' %}
{% block content %}
  <h1>お店情報の{{ object|yesno:'更新,作成'}}</h1>
  <form action="" method="post" >{% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="submit btn btn-outline-success">{{ object|yesno:'更新,作成'}}</button>
  </form>
  <p> </p>
  <div>
    <a href='JavaScript:history.back()' class='btn btn-outline-secondary'>&lt; 戻る</a>
  </div>
{% endblock %}

bestdish/templates/bestdish/shop_list.html
{% extends 'layout.html' %}
{% block content %}
  <h1>お店一覧</h1>
  <p>
  {% if user.is_authenticated %}
    <a href="{% url 'bestdish:create' %}" class='btn btn-outline-primary'>新しいお店</a>
  {% endif %}
  <table class="table table-striped table-hover">
  </p>
    <tr>
      <td>カテゴリ</td><td>店名</td><td>住所</td>
    </tr>
    {% for shop in object_list %}
    <tr>
      <td>{{ shop.category.name }}</td>
      <td><h4><a href='{% url "bestdish:detail" shop.pk %}' class='badge badge-warning'>{{ shop.name }}</a></h4></td>
      <td>{{ shop.address }}</td>
    </tr>
   {% endfor %}
  </table>
{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name='viewport' content='width=device-width, initial-scale=1, shrink-to-fit=no'>
    <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css'>
    <title>Best Dish</title>
    <style>body {padding-top: 80px;}</style>
  </head>
  <body>
    <nav class='navbar navbar-expand-sm navbar-dark bg-danger fixed-top'>
      <a class='navbar-brand' href='{% url "bestdish:index" %}'>Best Dish</a>
      <ul class="navbar-nav">
        {% if user.is_authenticated %}
          <div>　</div>
          <li class="nav-item">
            <span class="navbar-text">{{ user }}</span>
          </li>
          <div>　</div>
          <li class="nav-item">
            <a href='{% url "logout" %}' class='logout nav-link'>Logout</a>
          </li>
        {% else %}
          <div>　</div>
          <li class="nav-item">
            <a href='{% url "login" %}' class='login nav-link'>Login</a>
          </li>
          <div>　</div>
          <li class="nav-item">
            <a href='{% url "accounts:signup" %}' class="signup nav-link"> Sign up </a>
          </li>
        {% endif %}
      </ul>
    </nav>
    <div class='container'>
      {% block content %}
      {% endblock %}
    </div>
  </body>
</html>